name: custom_window
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.220
  window_manager: ^0.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - packages/custom_window/assets/images/close_icon.png
    - packages/custom_window/assets/images/maximize_icon.png
    - packages/custom_window/assets/images/minimize_icon.png
    - packages/custom_window/assets/images/unmaximize_icon.png
