name: custom_window
description: Custom Window is a simple package for developing desktop applications using Flutter. This package empowers you to create applications with a custom-designed window, giving your desktop app a unique and professional look. Whether you're building a productivity tool, a creative application, or any other desktop software, this package provides the foundation you need.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.220
  window_manager: ^0.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/close_icon.png
    - assets/images/maximize_icon.png
    - assets/images/minimize_icon.png
    - assets/images/unmaximize_icon.png
  fonts:
    - family: WindowIcons
      fonts:
        - asset: assets/fonts/WindowIcons.ttf