/// Flutter icons WindowIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WindowIcons
///      fonts:
///       - asset: fonts/WindowIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WindowIcons {
  WindowIcons._();

  static const _kFontFam = 'WindowIcons';
  static const String? _kFontPkg = null;

  static const IconData close_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximize_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmaximize_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minimize_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
